In [4]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

TASK-**1**

In [5]:
df.isnull().sum()

customer_id      0
age              3
city             2
gender           0
annual_income    0
dtype: int64

In [6]:
df['age']=df['age'].fillna(df['age'].median())

In [7]:
df['city']=df['city'].fillna(df['city'].mode()[0])

In [8]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [9]:
df.isnull().sum()

customer_id      0
age              0
city             0
gender           0
annual_income    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(1)

In [11]:
df=df.drop_duplicates()

In [12]:
df.duplicated().sum()

np.int64(0)

TASK-**2**

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['gender']=le.fit_transform(df[['gender']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/tmp/ipykernel_1646/1213601853.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender']=le.fit_transform(df[['gender']])

In [14]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

en = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

city_encoded_array = en.fit_transform(df[['city']])

feature_names = en.get_feature_names_out(['city'])

df_city_encoded = pd.DataFrame(city_encoded_array, columns=feature_names, index=df.index)
df = pd.concat([df.drop('city', axis=1), df_city_encoded], axis=1)

In [15]:
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000         0.0          1.0
1            2  35.0       0          80000         1.0          0.0
2            3  35.0       0          60000         1.0          0.0
3            4  35.0       1         120000         0.0          1.0
5            5  40.0       1          95000         1.0          0.0

TASK-**3**

In [16]:
#Scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df['annual_income']=scaler.fit_transform(df[['annual_income']])
df['age']=scaler.fit_transform(df[['age']])

In [17]:
df

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.837117       1      -1.410970         0.0          1.0
1            2  0.204124       0       0.036179         1.0          0.0
2            3  0.204124       0      -0.687396         1.0          0.0
3            4  0.204124       1       1.483328         0.0          1.0
5            5  1.224745       1       0.578860         1.0          0.0

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df['annual_income']=scaler.fit_transform(df[['annual_income']])
df['age']=scaler.fit_transform(df[['age']])

In [19]:
df

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000         0.0          1.0
1            2  0.666667       0         0.5000         1.0          0.0
2            3  0.666667       0         0.2500         1.0          0.0
3            4  0.666667       1         1.0000         0.0          1.0
5            5  1.000000       1         0.6875         1.0          0.0

StandardScaler → use when data is roughly normal and may have outliers; it centers data around 0 with unit variance.

MinMaxScaler → use when you need values in a fixed range (0–1), especially for neural networks and when there are no strong outliers.Fits value between 0 to 1.